#!/usr/bin/env bash
#
# This file have been generated by the following command :
# git gamble hook enable sound
#
# This hook can be disabled by executing the following command :
# git gamble hook disable sound
set -o errexit -o nounset -o pipefail -o errtrace

GAMBLED="$1"
ACTUAL="$2"

DEFAULT_PLAY_COMMAND="cvlc --quiet --play-and-exit"
PLAY_COMMAND="${PLAY_COMMAND:-$DEFAULT_PLAY_COMMAND}"

GOOD_SOUNDS=(
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/petite_corne.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/tres_bien.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/allez_vous_reposer_vous_l_avez_bien_merite.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_beau_quand_meme.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_bien_fait.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/la_dedans_carbure.mp3"
)

WRONG_SOUNDS=(
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/oui_ben_non.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais-pas-du-tout.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/peur_justifiee.mp3"
)

AMBIGUOUS_SOUNDS=(
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_nan_mais_quand_on_est_pas_habitue_c_est_drolement_impressionnant_la_magie.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah-une-vache-pres-cest-pas-une-science-exacte.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/apres_pour_le_detail_je_sais_pas.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/il-n-y-a-pas-dequivoque-vous-etes-franchement-un-bourrin.mp3"
    "https://kaamelott-soundboard.2ec0b4.fr/sounds/un_bon_quart_dheure.mp3"
)

if [ -n "${KAAMELOTT_FAN-}" ]; then
    GOOD_SOUNDS+=(
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/putain_il_est_fort_ce_con.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/a_mon_epoque_ca_se_faisait_pas.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/a_voui_vous_avez_raison.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_cest_ca.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/allez-y-mollo-avec-la-joie.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/avez_de_la_chance.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_pas_faux1.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_pas_faux2.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/demi_journee_vous_attend.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/euh_donc_pour_le_moment_on_le_crame_pas.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/il_m_aura_fait_chier_jusqu_au_bout_celui_la.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/il-est-fort-le-salaud.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/jvous_fait_confiance.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_evidemment_que_si.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mavez_lair_en_forme_vous_ce_soir.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/merciiiii.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh_putain_oui.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ouais_ca_aussi.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ouais_cest_mortel_ouais.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/putain_il_est_fort_ce_con.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/si_vous_etes_vendeur.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/voila_cest_pro.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vraiment_impressionnant.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/wooouuuhouhouhou_c_est_mortel.mp3"
        "${AMBIGUOUS_SOUNDS[@]}"
    )
    WRONG_SOUNDS+=(
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/il_ne_comprennent_jamais_le_code.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/2_3_poils_de_Q.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_ah_ah_les_pegus.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_bah_ouais_mais_apres_il_faut_un_peu_de_technique.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_cest_ca.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_non_la_aujourd_hui_ca_passera_pas.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah_ouais_je_l_ai_fait_trop_fulgurant_la_ca_va.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ah-non-vous-allez-pas-bouder.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/allez_boire_un_coup.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/alors_moi_jai_un_petit_probleme__jai_pas_pige_un_broc_de_ce_que_vous_bavez.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/arretez_immediatement_de_me_prendre_pour_une_truite.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/attendez_il_faut_que_ca_soit_vrai_tout_ce_qu_on_dit_la.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/bah-on-a-pas-de-technique-mais-cest-comme-tout.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/bon_bah_ca_va_on_plaisante.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/bon_bah_je_vais_voir_ce_que_je_peux_faire.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/bon_je_peux_pas_penser_a_tout_la.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/c_est_maintenant_quil_faut_se_secouer.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/C_est_pas_comme_si_on_passait_pour_des_glands_tous_les_jours.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ca_me_ferait_mal.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ca_va_encore_faire_des_discussions_a_rallonge.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ca_va_un_peu_trop_vite_pour_moi.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ca_vous_ennuie_si_je_vomis.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ca-ca-doit-etre-du-code-parce-que-ca-veut-rien-dire.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/casuffit.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/catastrophe.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_de_la_merde_2.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_de_la_merde.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_debile_cette_histoire.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_honteux.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest_une_catastrophe_souffle.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest-de-la-daube.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest-de-la-merde-merci-messieurs.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest-de-la-merde.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest-un-scandale.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/cest-une-blague.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/crame_ta_famille.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/dites_tout_de_suite_que_j_ai_des_idees_de_tocard.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ecoutez_je_comprend_rien_a_ce_que_vous_faites.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/enfin-quand-cest-demande-gentiment.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/et_cest_de_la_merde.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/et_puis_quoi_encore.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/et-bah-tu-peux-te-la-garder.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/faut-y-aller-a-la-zob.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/il_pige_rien_a_rien.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/inattendu.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/jai_rien_compris.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/le-votre-aussi-cest-de-la-merde.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/lui_on_comprend_ni_ce_qu_il_dit_ni_ce_qu_il_fait.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/maintenant-il-faut-nous-ecouter-parce-que-la-on-en-a-gros.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_faut_pas_deconner_ils_y_sont_pour_rien.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_qu_est_ce_que_vous_me_bavez_encore.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_qu_est_ce_que_vous_voulez_que_ca_me_foute_vos_conneries.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_qu_est_ce_que_vous_voulez_que_ca_me_foute.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_qu_est_ce_qui_vous_prend_ca_va_pas_vous_etes_dingue.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_vous_savez_ce_que_ca_veux_dire_au_moins.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais_ya_rien_a_developper_cest_de_la_merde_cest_tout.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais-allez-y-cest-pour-vous-stimuler-bon-dieu.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/mais-pas-du-tout.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/merde-la-ca-vous-va-ca.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/moi_je_serais_vous_je_vous_ecouterais.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/moi-je-serais-vous-je-vous-ecouterais.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/nan_la_sans_deconner_cest_zero.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/nan-ca-va-pas-etre-possible-ca.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/nan-cest-nimporte-quoi.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/nan-mais-quand-meme.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/non-mais-franchement-je-serais-nous-je-vous-ecouterais.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh_ca_fait_rien.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh_cest_la_vacherie_ca.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh_et_puis_j_en_ai_marre.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh_la_vache.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh-la-vache-mais-cest-nul.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh-mais-vous-etes-des-malades.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/oh-non-mais-il-y-a-des-jours-vous-deconnez-sec.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ok_on_va_arreter_le_tire_avec_les_defis.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/on_est_pas_sorti_du_sable.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/parce-que-vous-etes-en-train-de-faire-une-connerie-la-quand-meme.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/pas-moyen-de-piger-un-broc-de-ce-quil-dit.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/ptetre_une_connerie.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/qu-est_ce_dire_que_ceci.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/qu-est-ce-que-cest-cette-tisane.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/qu-est-ce-qui-a-dautre-qui-pue-sinon.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/quand_je_comprends_pas_je_reponds_pas.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/quicher-tete.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/quoi-mais-cest-un-scandale.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/sans_deconner.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/sortez-vous_les_doigts_du_cul.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/soupcon_gros_nul.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_admettrez_que_vous_etes_hors_normes.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_comprenez_le_principe.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_deconnez.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_devriez_commencer_par_organiser_le_merdier_que_vous_avez_la_dedans.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_etes_completement_con.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_etes_un_gros_nul.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous_rigolez_jespere.mp3"
        "https://kaamelott-soundboard.2ec0b4.fr/sounds/vous-pouvez-aller-vous-gratter.mp3"
        "${AMBIGUOUS_SOUNDS[@]}"
    )
fi

SOUNDS=()

if [ "${GAMBLED}" = "${ACTUAL}" ]; then
    SOUNDS=("${GOOD_SOUNDS[@]}")
else
    SOUNDS=("${WRONG_SOUNDS[@]}")
fi

SOUND="${SOUNDS[${RANDOM_SEED:-$RANDOM} % ${#SOUNDS[@]}]}"

$PLAY_COMMAND "$SOUND"
